import type { Opportunity } from "@/components/opportunities/opportunity-card"

export const opportunities: Opportunity[] = [
  {
    id: "1",
    title: "UNESCO Fellowship for Women in Science 2026",
    organization: "UNESCO",
    location: "Global",
    deadline: "2026-05-15",
    type: "Fellowship",
    fundingType: "Fully Funded",
    region: "Global",
    description: "A prestigious fellowship program supporting women researchers in life sciences, physical sciences, mathematics, and engineering.",
    isFeatured: true,
  },
  {
    id: "2",
    title: "Chevening Scholarship for Women Leaders",
    organization: "UK Government",
    location: "United Kingdom",
    deadline: "2026-04-20",
    type: "Scholarship",
    fundingType: "Fully Funded",
    region: "Europe",
    description: "Full scholarship for one-year Master's degree in any subject at any UK university. Open to women leaders worldwide.",
    isFeatured: true,
  },
  {
    id: "3",
    title: "Google Women Techmakers Scholarship",
    organization: "Google",
    location: "Global",
    deadline: "2026-06-01",
    type: "Scholarship",
    fundingType: "Partially Funded",
    region: "Global",
    description: "Scholarship for women pursuing computer science degrees. Includes financial support and Google mentorship.",
    isFeatured: true,
  },
  {
    id: "4",
    title: "African Women in Tech Internship",
    organization: "Microsoft",
    location: "Kenya, Nigeria, South Africa",
    deadline: "2026-04-30",
    type: "Internship",
    fundingType: "Fully Funded",
    region: "Africa",
    description: "12-week paid internship program for African women studying computer science or related fields.",
  },
  {
    id: "5",
    title: "UN Women Peace Fellowship",
    organization: "United Nations",
    location: "New York, USA",
    deadline: "2026-05-25",
    type: "Fellowship",
    fundingType: "Fully Funded",
    region: "North America",
    description: "Fellowship for women working in peacebuilding and conflict resolution. Includes living stipend and travel.",
  },
  {
    id: "6",
    title: "Women in Renewable Energy Grant",
    organization: "IRENA",
    location: "Global",
    deadline: "2026-06-15",
    type: "Grant",
    fundingType: "Fully Funded",
    region: "Global",
    description: "Research grants for women scientists and entrepreneurs working in renewable energy solutions.",
  },
  {
    id: "7",
    title: "Asia Women Leadership Conference 2026",
    organization: "Asian Development Bank",
    location: "Singapore",
    deadline: "2026-04-10",
    type: "Conference",
    fundingType: "Partially Funded",
    region: "Asia",
    description: "Annual conference bringing together women leaders from across Asia to discuss economic development and leadership.",
  },
  {
    id: "8",
    title: "Program Manager - Women's Health Initiative",
    organization: "Gates Foundation",
    location: "Seattle, USA",
    deadline: "2026-05-01",
    type: "Job",
    fundingType: "Self-Funded",
    region: "North America",
    description: "Full-time position managing women's health programs across developing countries.",
  },
  {
    id: "9",
    title: "European Women in Business Scholarship",
    organization: "INSEAD",
    location: "France / Singapore",
    deadline: "2026-06-30",
    type: "Scholarship",
    fundingType: "Partially Funded",
    region: "Europe",
    description: "MBA scholarship for women demonstrating exceptional leadership potential and commitment to advancing women in business.",
  },
  {
    id: "10",
    title: "Latin America Women Entrepreneurs Grant",
    organization: "IDB Lab",
    location: "Latin America",
    deadline: "2026-05-20",
    type: "Grant",
    fundingType: "Fully Funded",
    region: "South America",
    description: "Startup grants for women entrepreneurs in Latin America focusing on social impact and innovation.",
  },
  {
    id: "11",
    title: "Australia-ASEAN Women in STEM Fellowship",
    organization: "Australian Government",
    location: "Australia",
    deadline: "2026-07-15",
    type: "Fellowship",
    fundingType: "Fully Funded",
    region: "Oceania",
    description: "Research fellowship for women scientists from ASEAN countries to collaborate with Australian institutions.",
  },
  {
    id: "12",
    title: "Climate Action Internship for Women",
    organization: "WWF",
    location: "Switzerland",
    deadline: "2026-04-25",
    type: "Internship",
    fundingType: "Partially Funded",
    region: "Europe",
    description: "6-month internship program for young women passionate about environmental conservation and climate action.",
  },
]

export const blogPosts = [
  {
    id: "1",
    title: "10 Tips for Writing a Winning Scholarship Essay",
    excerpt: "Master the art of scholarship essay writing with these proven strategies that have helped thousands of women secure funding.",
    category: "Application Tips",
    author: "Dr. Sarah Chen",
    date: "2026-03-28",
    readTime: "5 min read",
  },
  {
    id: "2",
    title: "Breaking Barriers: Women in STEM Leadership",
    excerpt: "Inspiring stories of women who have risen to leadership positions in science, technology, engineering, and mathematics.",
    category: "Leadership",
    author: "Maya Rodriguez",
    date: "2026-03-25",
    readTime: "8 min read",
  },
  {
    id: "3",
    title: "How to Build a Strong Professional Network",
    excerpt: "Networking strategies specifically designed for women navigating professional spaces and building meaningful connections.",
    category: "Career Growth",
    author: "Amina Okonkwo",
    date: "2026-03-22",
    readTime: "6 min read",
  },
  {
    id: "4",
    title: "From Application to Acceptance: A Fellowship Journey",
    excerpt: "A first-hand account of navigating the fellowship application process and tips for success.",
    category: "Success Stories",
    author: "Lisa Park",
    date: "2026-03-18",
    readTime: "7 min read",
  },
]

export const resources = [
  {
    id: "cv-tips",
    title: "CV Writing Guide",
    description: "Create a compelling CV that highlights your achievements and stands out to selection committees.",
    icon: "FileText",
  },
  {
    id: "sop-guide",
    title: "Statement of Purpose Tips",
    description: "Craft a powerful personal statement that tells your unique story and demonstrates your potential.",
    icon: "PenTool",
  },
  {
    id: "interview-prep",
    title: "Interview Preparation",
    description: "Prepare for scholarship and job interviews with confidence using our comprehensive guide.",
    icon: "MessageSquare",
  },
  {
    id: "application-guide",
    title: "Application Checklist",
    description: "Never miss a requirement with our detailed checklist for scholarship and fellowship applications.",
    icon: "CheckSquare",
  },
]

export const regions = [
  { name: "Africa", count: 45, description: "Opportunities across 54 African nations" },
  { name: "Asia", count: 62, description: "Scholarships and programs throughout Asia" },
  { name: "Europe", count: 78, description: "EU and European institution opportunities" },
  { name: "North America", count: 56, description: "US, Canada, and Mexico programs" },
  { name: "South America", count: 34, description: "Latin American opportunities" },
  { name: "Oceania", count: 23, description: "Australia, New Zealand, and Pacific Islands" },
  { name: "Global", count: 89, description: "Worldwide and remote opportunities" },
]

export const opportunityTypes = [
  { name: "Scholarships", count: 120, description: "Academic funding for degrees worldwide" },
  { name: "Fellowships", count: 85, description: "Research and professional development" },
  { name: "Jobs", count: 156, description: "Career opportunities for women" },
  { name: "Internships", count: 94, description: "Hands-on learning experiences" },
  { name: "Grants", count: 67, description: "Funding for projects and research" },
  { name: "Conferences", count: 43, description: "Networking and learning events" },
]
